name: terraform deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
        TERRAFORM_VERSION: 1.0.4
      run: |
        wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -O /tmp/terraform.zip && unzip /tmp/terraform.zip -d/usr/bin && rm /tmp/terraform.zip
        export branch=${GITHUB_REF##*/}
        echo $branch 
        cd infrastructure
        terraform init -no-color
        terraform apply -no-color -auto-approve
