name: Publish to AWS Cloudfront

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key}}

      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0 # Fetch all history for git info
      #
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 22
      # - name: Install Dependencies
      #   run: npm ci
      # - name: Build Quartz
      #   run: |
      #     npx quartz build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9

      - name: Deploy
        run: |
          # Deploy
          cd infrastructure
          terraform init
          # terraform apply -auto-approve

      - name: Invalidate
        run: |
          aws cloudfront create-invalidation --distribution-id "$(terraform output -raw cloudfront_distribution_id)" --paths "/*"
